### PR TITLE
Restructure and Organised to clean up folder

### PR DESCRIPTION
**Pull request by umeshSinghVerma**
The image assets are transferred into the folder named assets and the file index.css is moved to Stylesheet folder and index.js to functionality folder
fixes #1

### CODE REVIEW

**Comment by umeshSinghVerma** [comment]
Screenshot from 2023-02-05 13-22-27
Screenshot from 2023-02-05 13-22-23
Screenshot from 2023-02-05 13-22-32
Screenshot from 2023-02-05 13-22-38

fixes #1

**Comment by Ilikepizza2** [comment]
Hello @umeshSinghVerma 
Pretty nice work! 
However, as suggested in the rules, unfortunately I can't accept the PR until you've been assigned the issue. Kindly comment on the issue so that I can assign you this.

**Comment by umeshSinghVerma** [comment]
> Hello @umeshSinghVerma Pretty nice work! However, as suggested in the rules, unfortunately I can't accept the PR until you've been assigned the issue. Kindly comment on the issue so that I can assign you this.

sir means i have to write down in issue in comment to assign me this work

**Comment by Ilikepizza2** [comment]
Yes! 
And kindly make seperate PRs for different issues

**Comment by Ilikepizza2** [comment]
I'm closing this PR since this PR includes different commits which aren't related to this issue. Kindly create new separate PRs for issues.

**Comment by umeshSinghVerma** [comment]
Ok Thankyou very much sir I had made a new pull request with the branch name issue1

**Pull request closed without merging**
