### PR TITLE
Added dark-light mode default preference + toggle-mode button fixed #4

### PR DESCRIPTION
**Pull request by destroycompiler**
fixed issue #4 : Added dark mode support

---

## Added Features
---
1. Website loads preferred color scheme by default

- By default, the website switches to the preferred mode of the browser, which I accomplished by putting an `@media` query with the `prefers-color-scheme: dark` argument.
- I have initialized color variables to `:root` (HTML) element throughout the website which change if the default preferred color scheme changes.
- As the variables change, the color mode of the entire website changes.
---
2. Toggle button on the top right section of the header to switch the color scheme

---

> button image

Screenshot_20230206_161747

---

- Instead of adding a new class manually to each element, the initialized color variables to the `:root` (HTML) element change when the button clicks, and so does the entire color scheme of the website.

- Change occurs with a transition of 0.5s so it doesn't look sudden.

https://user-images.githubusercontent.com/11803841/216953607-bc09f288-78dd-455f-ab7c-218fef08d632.mp4

---

> Added proper comments throughout my code to explain the JS logic and  CSS properties.
> The `toggle-mode` button is **responsive** with the website.

### CODE REVIEW

**Comment by destroycompiler** [comment]
Thank you for describing the proper procedure, sorry I couldn't figure out the order to follow, but now I understand.

- My code is such, That it is solving the first and the second issue simultaneously, since I didn't know in the starting, I solved all three issues in one commit only. So now I can't split the commits. 

Sir could you assign me points on the basis of this commit only as I cant split this single commit now?

Thank you sir

**Comment by Ilikepizza2** [comment]
It's okay @destroycompiler, I can consider that you added the toggle for the first two issues. But you will have to split the PR for the third issue otherwise the points can't be awarded.
To fix it, you can remove the prefer-dark-mode property from the code and push it again. It will automatically update this PR. And after that, you can create a new branch from this branch for the third issue. I know all this might sound redundant but this is how real open source works to avoid any confusion. :)

**Comment by destroycompiler** [comment]
Thank you sir for explaining the correct procedure. I will work on it soon.

**Comment by destroycompiler** [comment]
I have solved the first and second issues in the above commit bfefeb3.

**Comment by Ilikepizza2** [comment]
Nice work

**Comment by Ilikepizza2** [comment]
Great work @destroycompiler

**Pull request closed without merging**
