### PR TITLE
Increased the readability of Message me button

### PR DESCRIPTION
**Pull request by Harshs0891**
Fixes : #3 
Increased the readability of  Message me button by increasing the font opacity and font weight and added the feature of transform(scale) to the button.
here is the screenshot of(on hover effect):

button

### CODE REVIEW

**Comment by Ilikepizza2** [comment]
@Harshs0891 As said in the rules, kindly attach the screenshots with your PR.

**Comment by Harshs0891** [comment]
@Ilikepizza2 I have attached the screenshot plz consider it

**Comment by Ilikepizza2** [comment]
Good work @Harshs0891 
Accepted!

**Comment by Harshs0891** [comment]
Thank You Sir

**Pull request closed without merging**
